const slides = [
	{
		name: 'Tone',
		city: 'Målselv',
		text: `Hei alle sammen som følger disse nydelige menneskene og det fantastiske arbeidet de gjør for andre mennesker jeg må få lov å rette en stooooor gledelig takk for den positive opplevelsen dere har gitt meg og for de nye verktøyene dere har gitt meg i form av tanke kraft, positiv tenkning og lyst syn på livet. \n\nJeg har virkelig fått en “wake up call”.Og jeg skal virkelig fortsette det positive arbeidet dere har startet for meg. Jeg er så gla for at dere har gitt "et spark i baken" om jeg må få kalle det for det. Dere har hjulpet meg å bli kvitt tung energi i huset og dere har gjort hverdagene mine så mye lettere. Jeg kan stå opp å føle meg uthvilt og faktisk ha energi til helt uante ting:-) Jeg er til og med våken når jeg skal sove på kveldeneog det er fantastisk morsomt. Når alle andre ligger å snorker så dyna flagrer så ligger jeg og ser på tærne mine og tenker i mørket og ser ut av vinduet og kaster fra meg gamle tanker og ting som har tynget meg leeeeenge. En ny epoke i mitt liv har startet og jeg kan takke GAIA for det.Tusen hjertelig takk for så mye og flott hjelp. \n\nDere har virkelig gitt av dere selv og hatt all verdens av tid til å lytte og hjelpe og analysere og balansere og heale.Jeg har ikke ord for hvor glad jeg er for denne opplevelsen. Jeg oppfordrer alle til å ta kontakt med GAIA for det kommer garantert noe godt utav det. Ikke vent pga skepsis eller sånne ting. De er hyggelige snille og morsomme og trivelige mennesker som bare vil hjelpe andre og gjøre oss godt.Hvor mange sånne har vi egentlig rundt oss i en ellers så travel hverdag?Ikke mange nei.Jeg føler at jeg har fått to nye hjertevenner om har gitt meg en ny måte å se på livet på og en mer positiv måte å leve på.Hadde dere vært nærmere så skulle dere fått hver sin stooore bamseklem.Jeg vil gjerne holde kontakten med dere fremover. For alltid i mitt hjerte.<3\n\n`,
	},
	{
		name: 'Lise',
		city: 'Gresvik',
		text: `Hei! Vil gjerne få skrive noen ord om mitt forhold til Gaia. Jeg har hatt kontakt med disse to hjertegode menneskene i en del måneder å.Mitt liv er i dag helt forandret fra da jeg tok kontaktførste gang. dag lever jeg et nydelig liv, tidligere eksisterte jeg bare. Jeg har slitt psykisk så langt tilbake jeg kan huske. Har gått hos psykiater i 10 år uten å komme noe særlig lenger enn til utgangspunktet. Etter noen healinger og endel samtaler med disse to er altså livet mitt endret seg. Jeg vil gjerne si til Dere som sliter der ute, ta kontakt med Gaia. Hvis du føler eller har lyst til å kontakte Dem så bare gjør det med en gang. Ikke la den fysiske hjernen din få lov til å begynne å rote det til for deg. Bare send de en melding og De tar fort kontakt med deg. Er du ikke glad i å snakke i tlf eller ikke vet hva du skal si så ordner alt seg når du snakker med de. Det er for det meste de som snakker så det går veldig greit. Ikke nøl,men ta kontakt. Du vil ikke angre, jeg lover deg.`,
	},

	{
		name: 'Lisbeth EMilie',
		city: 'Fredrikstad',
		text: `Jeg hadde kontakt første gang med GAIA oktober 2013. Det ble ikke noe ut av det, jeg ringte ikke. Fortsatte å lese innleggene deres med interesse hver dag. Hadde lyst å ringe, men noe holdt meg tilbake. I februar 2014 tok jeg endelig kontakt og angrer ikke en dag på det.Jeg var da veldig sliten og bar jeg som mange med meg ting fra fortiden som jeg måtte ha hjelp til. Jeg fikk en enestående hjelp, fikk et verktøy å jobbe med, det var til stor hjelp.Likedan fikk jeg healing 2 ganger, som hjalp utrolig mye.Er det noe jeg lurer på eller problemer så er det bare å ringe dem.De er så enestående mennesker, og vil hele tiden det beste for deg.Jeg har kommet et godt stykke på veg, men det kan hende jeg trenger healing, da tar jeg kontakt. Vet da at det hjelper veldig bra. Blir alltid så godt humør av å snakke med dem, utrolig positive personer. Jeg vil anbefale GAIA på det sterkeste dersom du går å sliter med ting i livet ditt.Ikke gjør som jeg gjorde, nølte i 4 måneder. Ta kontakt med dem, jeg vet du får hjelp.Jeg er veldig glad jeg gjorde det. Lykke til. :) Så vil jeg takke dere 2 flotte menneskene bak GAIA for den hjelpen dere gav meg, jobben gjorde jeg selv, men dere hadde verktøyet, slik at livet mitt ble så herlig å leve.`,
	},

	{
		name: 'Irene',
		city: 'Levanger',
		text: `Hei. Vil bare si at Gaia er ikke bare mange flotte visdomsord, men det er 2 flotte mennesker bak som ønsker å hjelpe. Takk for den hjelp og støtte dere har gitt meg når tingene har røynet på. Dere lytter og gir healing, noe som funker fantastisk. Ikke bare for meg, men også på mine nærmeste. Takk for at dere bryr dere. Gla i dokk!!`,
	},

	{
		name: 'Iren',
		city: 'Sarpsborg',
		text: `Har lyst til å skrive noen ord om disse to varme, hjelpsomme og positive menneskene som jeg har vært så heldig å bli kjent med. Etter å ha fulgt med på GAIA siden i lang tid, tok jeg endelig mot til meg til å ta kontakt. Fikk tilbake melding umiddelbart.Bare ring nå du.Åh hjelp var min første tanke, jeg har jo ikke penger nå og hva skal jeg si? Frykten var så absolutt ubegrunnet.Traff verdens herligste mennesker i den andre enden av telefonen.Praten gikk av seg selv.Fikk hjelp allerede første kvelden bare ved å prate med disse varme gode menneskene.Og at jeg ikke kunne betale med engang var ingen hindring. Trengte jeg hjelp NÅ,så får du hjelp NÅ, var svaret jeg fikk.Og dèt gjorde jeg !! Timer med prat, healinger og en hjertevarme som jeg aldri hadde forventet av to helt fremmende mennesker. TUSEN,tusen takk! Og de er der også i etterkant. Sendte en melding en dag det var litt tung, og det gikk ikke lange tiden før de ringte meg tilbake.Disse to flotte menneskene BRYR seg virkelig, de viser en kjærlighet og omtanke for sine medmennesker som varmer langt inn i sjelen. Vis du som leser dette går og lurer og vurderer å ta kontakt, GJØR DET...du kommer aldri til angre.Anbefaler disse to herlige personene på det sterkeste.Er dem evig takknemlig for hva de har gjort for meg. TUSEN takk for all god hjelp og støtte. Mange klemmer til dere fra meg.`,
	},

	{
		name: 'Eva',
		city: 'Kragerø',
		text: `Takk til dere to vakre strålende mennesker som har forandret mitt liv. Dere har vist meg en vei jeg alltid har ønsket å gå men ikke funnet før dere viste meg at jeg var verdifull og at jeg måtte gi meg selv kjærlighet for å klare å gi andre noe. Dere har bevist for meg at jeg har hjelpere som er hos meg. Jeg føler det av og til veldig sterkt når det dukker opp problemer. Jeg er ikke alene mer. Akkurat nå når jeg sitter å skriver føler jeg nærværet til Synnøve min svigermor veldig sterkt. Jeg hadde ingen tro på at dette gikk ann før jeg fikk bevis på det. I går så jeg med egene øyne at dere fikk et budskap fra andre siden som dere måtte bringe videre til de det gjaldt. Dette var ute på en konsert og til to av mine venner og alt dere så, og som ble sagt stemte.Dere har fått en gave som er redningen for mange mennesker. Jeg har hatt en samtale med min far en god samtale og det kan jeg ikke huske sist jeg hadde. Det har skjedd så utrolig mye i livet mitt etter den første healingen og alle samtalene vi har hatt. Smerter forsvinner Jeg har fred å føler glede, lykke og en enorm takknemlighet i meg. Jeg har en følelse av å være på en oppdagelse ferd i mitt indre og det blir mer og mer spennende å se nye ting. I går så jeg auran min som Hilde viste meg.Den var skinnende gul, og gikk rundt meg som en skisse utenfor meg selv. Sååå rart. Nå har jeg vel snart skrevet en hel bok, men meningen med det hele, er å si at mine verste traumer og smerter er blitt borte.Jeg lever virkelig livet. Vil alltid ha kontakt med dere mine skjønne, velsignede venner.Trenger en healing og en samtale av og til for det er som å bli født på ny.Håper at flere og flere som trenger det vil få det sånn som meg. Med kjærlig hilsen i takknemlighet og en Stooor varm klem til dere fra meg Eva.`,
	},
];

export default slides;
